name: Build iOS Dylib with Fishhook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install ldid
      run: brew install ldid

    - name: Build Hook dylib
      run: |
        clang++ -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -arch arm64 -fobjc-arc -miphoneos-version-min=12.0 \
          -shared src/hook.mm src/fishhook.c -o HookCod.dylib

    - name: Sign with ldid
      run: |
        ldid -Sent.plist HookCod.dylib

    - name: Upload dylib
      uses: actions/upload-artifact@v4
      with:
        name: HookCod.dylib
        path: HookCod.dylib
