name: Build Dylib

on:
  push:
    paths:
      - 'src/**'
      - 'toolchain/**'
      - '.github/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build dylib
        run: |
          chmod +x toolchain/build.sh
          toolchain/build.sh

      - name: Upload dylib
        uses: actions/upload-artifact@v3
        with:
          name: hook.dylib
          path: build/hook.dylib

