name: Build iOS Dylib

on:
  push:
    paths:
      - '**.mm'
      - '**/CMakeLists.txt'
      - '.github/workflows/build_dylib.yml'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build folder
        run: |
          mkdir -p build
          echo -e 'cmake_minimum_required(VERSION 3.13)\n\
project(Hook)\n\
set(CMAKE_OSX_SYSROOT iphoneos)\n\
set(CMAKE_OSX_ARCHITECTURES arm64)\n\
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fobjc-arc -std=c++17")\n\
add_library(hook SHARED hook.mm)' > CMakeLists.txt

      - name: Install CMake
        run: brew install cmake

      - name: Build dylib
        run: |
          cd build
          cmake .. -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES=arm64
          make

      - name: Upload dylib artifact
        uses: actions/upload-artifact@v3
        with:
          name: codm_patch_hook_dylib
          path: build/libhook.dylib
