name: Build iOS Dylib

on:
  push:
    paths:
      - '**.mm'
      - '**CMakeLists.txt'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (needed for CMake sometimes)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - name: Create build directory
        run: mkdir -p build

      - name: Configure project with CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build

      - name: Upload dylib artifact
        uses: actions/upload-artifact@v4
        with:
          name: hook-dylib
          path: build/lib/hook.dylib
