name: Build iOS Dylib

on:
  push:
    branches: [main]

jobs:
  build-dylib:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew install llvm
        brew install ldid

    - name: Compile Dylib
      run: |
        clang++ -std=c++17 -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -framework UIKit \
          src/hook.mm \
          -o codpatch.dylib

    - name: Code Sign Dylib
      run: |
        chmod +x /usr/local/bin/ldid || true
        ldid -S toolchain/ent.plist codpatch.dylib

    - name: Upload Dylib
      uses: actions/upload-artifact@v4
      with:
        name: codpatch.dylib
        path: codpatch.dylib
